### ISSUE TITLE
Integrations addition tracking feature

### ISSUE THREAD

**Issue by Shocktrooper** [xanzy/go-gitlab#1132]
### Purpose
To serve as  a wholistic tracking ticket of all of the services that are available via the API and what their integration progress into go-gitlab  This ticket should be kept up to date as new service integrations are released by GitLab and [go-gitlab](https://github.com/xanzy/go-gitlab) updates its services integration 

### Services Tracking list
Complete List of services sourced from [here](https://docs.gitlab.com/ce/api/services.html) on 4/19/21
This list was cross referenced from [here](https://github.com/xanzy/go-gitlab/blob/master/services.go) with the GitLab service API page
- [ ] Asana
- [ ] Assembla
- [ ] Atlassian Bamboo CI
- [ ] Bugzilla
- [ ] Buildkite
- [ ] Campfire
- [ ] Confluence service
- [x] Custom Issue Tracker
- [x] Drone CI
- [ ] Emails on push
- [x] External wiki
- [ ] Flowdock
- [x] GitHub
- [ ] Hangouts Chat
- [ ] Irker (IRC gateway)
- [x] Jenkins CI
- [ ] JetBrains TeamCity CI
- [x] Jira
- [x] Mattermost notifications
- [ ] Mattermost slash commands
- [x] Microsoft Teams
- [ ] MockCI
- [ ] Packagist
- [x] Pipeline-Emails
- [ ] PivotalTracker
- [x] Prometheus
- [ ] Pushover
- [ ] Redmine
- [x] Slack notifications
- [x] Slack slash commands
- [ ] Unify Circuit
- [ ] Webex Teams
- [x] YouTrack

### References
- https://github.com/xanzy/go-gitlab/blob/master/services.go
- https://docs.gitlab.com/ee/api/integrations.html

**Comment by sunny0826** [comment]
refer: https://docs.gitlab.com/ee/api/integrations.html#slack-slash-commands
> In GitLab 14.4, the services endpoint was [renamed](https://gitlab.com/gitlab-org/gitlab/-/issues/334500) to `integrations`. Calls to the Integrations API can be made to both `/projects/:id/services` and `/projects/:id/integrations`. The examples in this document refer to the endpoint at `/projects/:id/integrations`.  

Perhaps the `services` need to be renamed.

**Comment by Shocktrooper** [comment]
As a separate ticket we should probably switch https://github.com/xanzy/go-gitlab/blob/master/services.go to something like https://github.com/xanzy/go-gitlab/blob/master/integrations.go and its accompanying test file.

**Comment by Shocktrooper** [comment]
Actually a PR might be more worthwhile to add individual integrations to the main README with checkboxes like the other features.  I will make a PR for that instead of this ticket which can become out of date

**Comment by svanharmelen** [comment]
Sounds like a plan to me!

**Comment by svanharmelen** [comment]
Closing this one as I don't have the feeling this is either used or kept up-to-date...
