### ISSUE TITLE
Support the v4 API

### ISSUE THREAD

**Issue by johanbrandhorst** [xanzy/go-gitlab#151]
Lets track this in an issue. The GitLab API v3 is officially deprecated and will be supported until at least 9.3. Given the current release schedule (once per month), that means it will be unsupported 3 months from now.

I would like to be able to start consuming v4 functionality so I might start work on a v4 branch.

I think all current documentation links need to be updated to the v3 documentation as currently the links all point to the v4 documentation which causes confusion. Separately some effort should be made to start supporting v4 specific functionality (probably in a feature branch). Once both those things are completed, v3 could be spun out to a separate branch and v4 can be merged to master.

Below are the changes made between V3 and V4. A tickbox indicates that work has been completed on that change.

### Completed
- [x] Rename Build Triggers to be Pipeline Triggers API [!9713](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9713). Fixed in #152.
  - `POST /projects/:id/trigger/builds` to `POST /projects/:id/trigger/pipeline`
  - Require description when creating a new trigger `POST /projects/:id/triggers`
- [x] Removed `GET /projects/:search` (use: `GET /projects?search=x`) [!8877](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8877). Fixed in #161.
- [x] `iid` filter has been removed from `GET /projects/:id/issues` [!8967](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8967). Fixed in #161.
- [x] `GET /projects/:id/merge_requests?iid[]=x&iid[]=y` array filter has been renamed to `iids` [!8793](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8793). Fixed in #161.
- [x] Endpoints under `GET /projects/merge_request/:id` have been removed (use: `GET /projects/merge_requests/:id`) [!8793](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8793). Fixed in #161.
- [x] Project snippets do not return deprecated field `expires_at` [!8723](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8723). Fixed in #161.
- [x] Endpoints under `GET /projects/:id/keys` have been removed (use `GET /projects/:id/deploy_keys`) [!8716](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8716). Fixed in #161.
- [x] Update v3 documentation to point to archived v3 docs. Fixed in #160.
- [x] Return basic info about pipeline in `GET /projects/:id/pipelines` [!8875](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8875). Fixed in #163 
- [x] Renamed all `build` references to `job` [!9463](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9463). Fixed in #166.
- [x] Use `visibility` as string parameter everywhere [!9337](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9337). Fixed in #167.
- [x] Project filters are no longer available as `GET /projects/foo`, but as `GET /projects?foo=true` instead [!8962](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8962). Fixed in #170.
  - `GET /projects/visible` & `GET /projects/all` are consolidated into `GET /projects` and can be used with or without authorization
  - `GET /projects/owned` moved to `GET /projects?owned=true`
  - `GET /projects/starred` moved to `GET /projects?starred=true`
- [x] `GET /projects` returns all projects visible to current user, even if the user is not a member [!9674](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9674). Fixed in #170.
  - To get projects the user is a member of, use `GET /projects?membership=true`
- [x] Return HTTP status code `400` for all validation errors when creating or updating a member instead of sometimes `422` error. [!9523](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9523). Doesn't require changes.
- [x] Status 409 returned for `POST /projects/:id/members` when a member already exists [!9093](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9093). Doesn't require changes.
- [x] Remove `GET /groups/owned`. Use `GET /groups?owned=true` instead [!9505](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9505). Fixed in commit 62634b8.
- [x] Moved `POST /projects/fork/:id` to `POST /projects/:id/fork` [!8940](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8940). Fixed in commit 577e19d.
- [x] Renamed the `merge_when_build_succeeds` parameter to `merge_when_pipeline_succeeds` on the following endpoints: [!9335](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/)
  - `PUT /projects/:id/merge_requests/:merge_request_id/merge`
  - `POST /projects/:id/merge_requests/:merge_request_id/cancel_merge_when_pipeline_succeeds`
  - `POST /projects`
  - `POST /projects/user/:user_id`
  - `PUT /projects/:id`
- [x] Update endpoints for repository files [!9637](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9637). Fixed in commit a0b1dcb.
  - Moved `GET /projects/:id/repository/files?file_path=:file_path` to `GET /projects/:id/repository/files/:file_path` (`:file_path` should be URL-encoded)
  - `GET /projects/:id/repository/blobs/:sha` now returns JSON attributes for the blob identified by `:sha`, instead of finding the commit identified by `:sha` and returning the raw content of the blob in that commit identified by the required `?filepath=:filepath`
  - Moved `GET /projects/:id/repository/commits/:sha/blob?file_path=:file_path`  and `GET /projects/:id/repository/blobs/:sha?file_path=:file_path` to `GET /projects/:id/repository/files/:file_path/raw?ref=:sha`
  - `GET /projects/:id/repository/tree` parameter `ref_name` has been renamed to `ref` for consistency
- [x] Removed the following deprecated Templates endpoints (these are still accessible with `/templates` prefix) [!8853](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8853)
  - `/licences`
  - `/licences/:key`
  - `/gitignores`
  - `/gitlab_ci_ymls`
  - `/dockerfiles`
  - `/gitignores/:key`
  - `/gitlab_ci_ymls/:key`
  - `/dockerfiles/:key`
- [x] Moved `DELETE /todos` to `POST /todos/mark_as_done` and `DELETE /todos/:todo_id` to `POST /todos/:todo_id/mark_as_done` [!9410](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9410)
- [x] Return pagination headers for all endpoints that return an array [!8606](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8606)
- [x] Removed `DELETE /projects/:id/deploy_keys/:key_id/disable`. Use `DELETE /projects/:id/deploy_keys/:key_id` instead [!9366](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9366)
- [x] Moved `PUT /users/:id/(block|unblock)` to `POST /users/:id/(block|unblock)` [!9371](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9371)
- [x] Make subscription API more RESTful. Use `POST /projects/:id/:subscribable_type/:subscribable_id/subscribe` to subscribe and `POST /projects/:id/:subscribable_type/:subscribable_id/unsubscribe` to unsubscribe from a resource. [!9325](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9325)
- [x] Labels filter on `GET /projects/:id/issues` and `GET /issues` now matches only issues containing all labels (i.e.: Logical AND, not OR) [!8849](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8849)
- [x] Renamed param `branch_name` to `branch` on the following endpoints [!8936](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8936)
  - `POST /projects/:id/repository/branches`
  - `POST /projects/:id/repository/commits`
  - `POST/PUT/DELETE :id/repository/files`
- [x] Renamed `branch_name` to `branch` on `DELETE /projects/:id/repository/branches/:branch` response [!8936](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8936)
- [x] Remove `public` param from create and edit actions of projects [!8736](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/8736)
- [x] Remove `subscribed` field from responses returning list of issues or merge
  requests. Fetch individual issues or merge requests to obtain the value
  of `subscribed`
  [!9661](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9661)
- [x] Notes do not return deprecated field `upvote` and `downvote` [!9384](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9384)
- [x] Return 202 with JSON body on async removals on V4 API (`DELETE /projects/:id/repository/merged_branches` and `DELETE /projects/:id`) [!9449](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9449)
- [x] `GET /projects/:id/milestones?iid[]=x&iid[]=y` array filter has been renamed to `iids` [!9096](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9096)
- [x] Drop `GET /projects/:id/repository/commits/:sha/jobs` [!9463](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9463)
- [x] Simplify project payload exposed on Environment endpoints [!9675](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9675)
- [x] API uses merge request `IID`s (internal ID, as in the web UI) rather than `ID`s. This affects the merge requests, award emoji, todos, and time tracking APIs. [!9530](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9530)
- [x] API uses issue `IID`s (internal ID, as in the web UI) rather than `ID`s. This affects the issues, award emoji, todos, and time tracking APIs. [!9530](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9530)
- [x] Change initial page from `0` to `1` on `GET /projects/:id/repository/commits` (like on the rest of the API) [!9679] (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9679)
- [x] Return correct `Link` header data for `GET /projects/:id/repository/commits` [!9679] (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9679)

**Comment by svanharmelen** [comment]
Sounds good... I think this sums up our previous conversation pretty well. So fully agree on this approach and will also try to reserve some time for this in the coming months. 

Unfortunately I cannot make any strong commitments as I have a few internal projects that currently take a lot of my time. But I'm sure I can free up at least some hours...

**Comment by johanbrandhorst** [comment]
Could you create a v4 branch so I can submit merge requests against it?

Thanks

**Comment by svanharmelen** [comment]
Done: https://github.com/xanzy/go-gitlab/tree/f-api-v4

**Comment by Viperoo** [comment]
Hi,

Do you add support of [jobs](https://docs.gitlab.com/ce/api/jobs.html)?

**Comment by eguevara** [comment]
If not done already, can I take a stab at 
https://docs.gitlab.com/ee/api/todos.html

**Comment by svanharmelen** [comment]
@eguevara that's not done yet, so by all means! 👍 

Please do refer to the CE docs instead of the EE docs as I would like to keep this package compatible with the CE version.

And as guideline, please create a `TodosService` for this one and put the related code in a file called `todos.go`. That will keep things consistent.

Thanks!

**Comment by bgetsug** [comment]
@Viperoo support for the `jobs` API was merged to the `f-api-v4` branch in #166

**Comment by stevenorman** [comment]
I was going to have a look at some of the outstanding changes for this.  Would you prefer merge requests for each task in the list or could some be lumped together?

Also, how about merging changes from master into the v4 branch?  I had an MR merged last week and it probably needs to end up in branch.  I can raise a second MR for that if needed.

**Comment by dihedron** [comment]
Hallo, I have an issue with the way support for API v4 is being proposed. Please be aware that there are relevant scenarios where there is a need for **both** API v3 **and** v4 support at the same time. 

As an example, go-gitlab is vendored inside [HashiCorp's Terraform](https://github.com/hashicorp/terraform), where it is used to manage GitLab instances in a declarative way via a specific plugin. I am implementing a fully automated private cloud tenant provisioning/configuration system using Terraform at work and I know already that I'll be juggling with multiple GitLab instances, not all of them at the bleeding edge.

It seems to me that swapping out v3 and replacing it with v4 seals the destiny of go-gitlab as a thin API wrapper; supporting multiple API versions could make it an enterprise-class API library and widen its use.

Once the groundworks for multiple API version has been established, it will be possible to support v5, v6 etc. and phase out v3, v4 as GitLab releases go out of maintenance.

Thus, my proposal is to:
1. use explicit API versioning in the Client (e.g. a ClientV3, a ClientV4, or a common Client with an  "APIVersion" field)
2. then find a way to plug in API services according to version in order to reuse anything that has not changed from one version to the next;
3. use the Version API that was pulled into go-gitlab yesterday to negotiate the API version with the server; thus unless the user explicitly creates a "ClientVx", a factory func may contact the server and map the returned version number against the API support level (e.g. "8.13" -> "V3", "9.1" -> "V4" etc.)
4. Provide method implementations for both V3 and V4 APIs when they differ
5. where common parameters are marshalled differently (e.g. VisibilityLevel: "10" in V3, "private" in V4), provide custom marshalling based on context information, if not a different struct altogether with different annotations.

There might be other issues I'm not aware of; I just wanted to humbly put forward to you this caveat that single level API support is dramatically limiting in certain contexts, and these contexts are those in which I see automation via API most useful.

**Comment by svanharmelen** [comment]
@dihedron I understand your question/issue, but I think the proposed solution is one that would make things very complex and hard to maintain.

I still think there is a solution for your problem, but it will require some thinking and testing. So let me get back on this one once I have done a little prototyping.

**Comment by dihedron** [comment]
Cool! Let me know if I can help.

**Comment by svanharmelen** [comment]
I walked true all the remaining tasks and updated/changed things were needed. So I think we now have finished all changes needed to support the V4 API. There are new endpoints that are not yet supported (they don't currently exist in this package), but all the existing endpoints should now work correctly with the V4 API.

I'm closing this issue and will do the needed git magic later today (one more PR to merge before moving everything to master).

**Comment by johanbrandhorst** [comment]
Good job!
